# Generated by Django 2.2 on 2019-06-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boastsandroasts',
            name='boasts',
            field=models.CharField(default='boast?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='boastsandroasts',
            name='roasts',
            field=models.CharField(default='roast?', max_length=1000),
        ),
    ]
