# Generated by Django 2.2 on 2019-06-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_backend', '0002_auto_20190626_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boastsandroasts',
            name='boasts',
            field=models.CharField(blank=True, default='boast?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='boastsandroasts',
            name='roasts',
            field=models.CharField(blank=True, default='roast?', max_length=1000),
        ),
    ]
