# Generated by Django 2.2 on 2019-06-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_backend', '0003_auto_20190626_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastsandroasts',
            name='dateCreated',
            field=models.DateField(auto_now=True),
        ),
    ]
