# Generated by Django 2.2 on 2019-06-26 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_backend', '0004_boastsandroasts_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boastsandroasts',
            name='dateCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 26, 17, 7, 10, 350360)),
        ),
    ]
